# Generated by Django 5.2.5 on 2025-08-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListSense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='Definition', null=True)),
                ('exam', models.TextField(blank=True, help_text='Example', null=True)),
                ('wseq', models.IntegerField(default=0, help_text='Sequence')),
                ('wrkd', models.IntegerField(default=0, help_text='type_sense.id')),
                ('wrid', models.IntegerField(default=0, help_text='list_word.id')),
                ('dated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'list_sense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapAntonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'map_antonym',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapDerived',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dete', models.IntegerField(default=0, help_text='type_derived.derived_type')),
                ('wrig', models.IntegerField(default=0, help_text='irregular eg. 0-3')),
            ],
            options={
                'db_table': 'map_derived',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapSimilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'map_similar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapThesaurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'map_thesaurus',
                'managed': False,
            },
        ),
    ]
