# Generated by Django 5.2.5 on 2025-08-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listsense_mapantonym_mapderived_mapsimilar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDerived',
            fields=[
                ('derived_type', models.AutoField(primary_key=True, serialize=False)),
                ('derivation', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'type_derived',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='listsense',
            options={'managed': False, 'ordering': ['wseq']},
        ),
    ]
